train:
  ldmyaml: vqgan
  prj: null
  rotate: true
  resize: 0
  nm: "00"
  gan_mode: vanilla
  netG: ed023e
  norm: batch
  mc: true
  netD: patch_16
  ngf: 32
  ndf: 64
  final: none
  batch_size: 1
  n_epochs: 10001
  epoch_save: 100
  lr: 0.0002
  beta1: 0.5
  n_epochs_decay: 100
  lr_policy: cosine
  lr_decay_iters: 50
  adv: 1.0
  not_tracking_hparams: []
  models: ae0iso0tccutvqq
  cropz: 16
  cropsize: 128
  env: brcb
  direction: x3d0
  dataset: X2527T102MM
  lamb: 10
  nocut: false
  lbNCE: 0
  skipl1: 4
  l1how: max
  tc: false
  input_nc: 1
  output_nc: 1
